remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Techni's Peripheral Museum
description: This site contains all the novelty controllers/peripherals I own and want to own
